---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: publish
    image: plugins/gcr
    settings:
      repo: cyrus-containers/mmtbx
      tags:
        - ${DRONE_COMMIT_BRANCH}
      debug: true
      json_key:
        from_secret: dockerconfigjson

trigger:
  event:
    include:
    - push

node_selector:
  CPUs: 8