---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: publish
    image: gcr.io/cyrus-containers/drone-plugins/gcr:linux-amd64
    privileged: true
    settings:
      repo: cyrus-containers/mmtbx
      tags.normalize: true
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH}
      debug: true
      json_key:
        from_secret: dockerconfigjson

  - name: publish-tag
    image: gcr.io/cyrus-containers/drone-plugins/gcr:linux-amd64
    privileged: true
    settings:
      repo: cyrus-containers/mmtbx
      tags.normalize: true
      tags:
        - ${DRONE_TAG}
      debug: true
      json_key:
        from_secret: dockerconfigjson
    when:
      event: tag

trigger:
  event:
    include:
    - push

node_selector:
  CPUs: 8
